version: '3'
services:
  web:
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost.crt:/etc/certs/localhost.crt
      - ./docker/nginx/localhost-key.key:/etc/certs/localhost-key.key
    environment:
      - TZ=Asia/Tokyo