version: '3'
services:
  web:
    image: nginx:1.17-alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo